[package]
name = "minesweeper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_pcg = "0.3.0"
terminal_size = "0.1.16"
console = "0.14.1"
clap = "2.33.3"